# Site settings
title: Lydia Krifka-Dobes
# Site's name
name: Lydia Krifka-Dobes' Blog
author: Lydia Krifka-Dobes
email: oiooiioo@tuta.io
description: "sound + code + research"
baseurl: ""
url: "https://austinbostonberlin.github.io"

exclude: [vendor]
# TODO(max): Use pagefind (pagefind --source . --root-selector .container) but
# avoid scanning _site somehow.
include: [.well-known]

future: false

repo:
    repository_url: https://github.com/austinbostonberlin/austinbostonberlin.github.io
    branch: main

permalink: '/blog/:title/'
post_dirs: false

# Build settings
markdown: kramdown
kramdown:
    input: GFM # GitHub Flavored Markdown
    hard_wrap: false
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - rouge
